/**
 * Bounded discovery campaigns — sweep the scenario space, record what happened, emit regressions.
 *
 * The unknown-unknown problem is that the interesting failure is the one nobody wrote a test for.
 * A campaign does not know what it is looking for either; it knows how to combine the differences it
 * *can* express and to check each combination against invariants that must hold regardless.
 *
 * Two properties matter more than coverage:
 *
 *   **Bounded.** A campaign states its ceiling and stops there. An unbounded sweep that never
 *   finishes discovers nothing, and one that quietly truncates reports false confidence — so when a
 *   ceiling truncates the space, the report says so rather than presenting a partial sweep as whole.
 *
 *   **Deterministic.** Combinations are enumerated in a fixed order from named parts, so run N and
 *   run N+1 produce the same set and a discovery can be replayed by name rather than by luck.
 */

import {
  AUTHORITY_FAULTS_V1,
  PERTURBATIONS_V1,
  checkObservation,
  runScenario,
  type AuthorityFaultNameV1,
  type HarnessCheckV1,
  type HarnessInvariantV1,
  type HarnessScenarioV1,
  type PerturbationNameV1,
} from "./scenario.js";
import { createExperienceLedger, type ExperienceLedgerV1, type ExperienceProvenanceV1 } from "./ledger.js";

export interface CampaignBoundsV1 {
  /** Hard ceiling on scenarios executed. Reached means the sweep was truncated, and it is reported. */
  readonly maxScenarios: number;
}

export interface CampaignInputV1 {
  readonly campaignId: string;
  readonly perturbations: readonly PerturbationNameV1[];
  readonly authorityFaults: readonly AuthorityFaultNameV1[];
  /**
   * What must hold for *every* combination in the sweep.
   *
   * A campaign asserts a universal, not a per-case expectation: "a perturbed dispatch must never
   * write" is a claim about the whole space, and any combination that breaks it is a discovery.
   */
  readonly universalInvariants: readonly HarnessInvariantV1[];
  /** The combination that must still work, so a campaign cannot pass by refusing everything. */
  readonly controlInvariants: readonly HarnessInvariantV1[];
  readonly bounds: CampaignBoundsV1;
  readonly observedAtSha: string;
  readonly observedAtUtc: string;
  readonly provenance?: ExperienceProvenanceV1;
}

export interface CampaignDiscoveryV1 {
  readonly scenarioId: string;
  readonly perturbation: PerturbationNameV1;
  readonly authorityFault: AuthorityFaultNameV1;
  readonly violations: readonly string[];
  /** A runnable restatement of the case, so a discovery becomes a regression without re-derivation. */
  readonly regression: string;
}

export interface CampaignResultV1 {
  readonly campaignId: string;
  readonly executed: number;
  readonly spaceSize: number;
  readonly truncated: boolean;
  readonly controlHeld: boolean;
  readonly discoveries: readonly CampaignDiscoveryV1[];
  readonly ledger: ExperienceLedgerV1;
}

function scenarioIdFor(campaignId: string, perturbation: string, fault: string): string {
  return `${campaignId}:${perturbation}+${fault}`;
}

/** The regression a discovery becomes: a scenario literal a person can paste into a suite. */
export function regressionFor(discovery: Omit<CampaignDiscoveryV1, "regression">): string {
  return [
    "// Generated by a discovery campaign. This combination violated a universal invariant.",
    `// Violations: ${discovery.violations.join("; ")}`,
    "test(" + JSON.stringify(discovery.scenarioId) + ", () => {",
    "  const check = evaluateScenario({",
    `    id: ${JSON.stringify(discovery.scenarioId)},`,
    `    asks: ${JSON.stringify(`regression for ${discovery.perturbation} + ${discovery.authorityFault}`)},`,
    `    perturbEnvelope: PERTURBATIONS_V1.${discovery.perturbation},`,
    `    perturbGate: AUTHORITY_FAULTS_V1.${discovery.authorityFault},`,
    "    expect: [{ kind: \"NO_EFFECT\" }],",
    "  });",
    "  assert.equal(check.passed, true, check.violations.map((v) => v.detail).join(\"; \"));",
    "});",
  ].join("\n");
}

/**
 * Run one bounded campaign.
 *
 * The control case runs first and is reported separately. A campaign where everything refuses is not
 * a safe campaign, it is a broken one — and without the control there is no way to tell the two apart
 * from the outside.
 */
export function runCampaign(input: CampaignInputV1): CampaignResultV1 {
  const ledger = createExperienceLedger();
  const provenance = input.provenance ?? "HARNESS_CAMPAIGN";
  const discoveries: CampaignDiscoveryV1[] = [];

  // --- control: the unperturbed case must still do its work.
  const controlScenario: HarnessScenarioV1 = {
    id: `${input.campaignId}:control`,
    asks: "the valid dispatch still performs its effect, so a clean sweep is not blanket denial",
    expect: input.controlInvariants,
  };
  const control = checkScenario(controlScenario);
  ledger.record({
    entryId: controlScenario.id,
    attempted: "unperturbed valid dispatch",
    observed: describe(control),
    learned: control.passed ? "the valid path still performs its effect" : "the valid path stopped working",
    outcome: control.passed ? "HELD" : "VIOLATED",
    provenance,
    observedAtSha: input.observedAtSha,
    observedAtUtc: input.observedAtUtc,
    scenarioId: controlScenario.id,
    violations: control.violations.map((v) => `${v.invariant}: ${v.detail}`),
  });

  // --- sweep, in a fixed order, up to the stated ceiling.
  const combinations: { perturbation: PerturbationNameV1; fault: AuthorityFaultNameV1 }[] = [];
  for (const perturbation of input.perturbations) {
    for (const fault of input.authorityFaults) {
      if (perturbation === "none" && fault === "none") continue; // that is the control
      combinations.push({ perturbation, fault });
    }
  }

  const executable = combinations.slice(0, Math.max(0, input.bounds.maxScenarios));
  for (const { perturbation, fault } of executable) {
    const scenario: HarnessScenarioV1 = {
      id: scenarioIdFor(input.campaignId, perturbation, fault),
      asks: `does ${perturbation} combined with ${fault} still respect the universal invariants?`,
      perturbEnvelope: PERTURBATIONS_V1[perturbation],
      perturbGate: AUTHORITY_FAULTS_V1[fault],
      expect: input.universalInvariants,
    };
    const check = checkScenario(scenario);
    const violations = check.violations.map((v) => `${v.invariant}: ${v.detail}`);

    ledger.record({
      entryId: scenario.id,
      attempted: `${perturbation} + ${fault}`,
      observed: describe(check),
      learned: check.passed ? "" : "a perturbed dispatch produced an effect it should not have",
      outcome: check.passed ? "HELD" : "VIOLATED",
      provenance,
      observedAtSha: input.observedAtSha,
      observedAtUtc: input.observedAtUtc,
      scenarioId: scenario.id,
      violations,
    });

    if (!check.passed) {
      const partial = { scenarioId: scenario.id, perturbation, authorityFault: fault, violations };
      discoveries.push({ ...partial, regression: regressionFor(partial) });
    }
  }

  return {
    campaignId: input.campaignId,
    executed: executable.length + 1,
    spaceSize: combinations.length + 1,
    truncated: executable.length < combinations.length,
    controlHeld: control.passed,
    discoveries,
    ledger,
  };
}

function checkScenario(scenario: HarnessScenarioV1): HarnessCheckV1 {
  const run = runScenario(scenario);
  return checkObservation(scenario.id, run.observation, scenario.expect);
}

function describe(check: HarnessCheckV1): string {
  const { writes, decisions, outcomeClass, threw } = check.observation;
  return `writes=${writes.length} decisions=${decisions.length} outcome=${outcomeClass ?? "none"}${threw === null ? "" : ` threw=${threw}`}`;
}
